packages:
  - "optuna_dashboard"
  - "standalone_app"
  - "vscode"
  - "tslib/types"
  - "tslib/storage"
  - "tslib/react"

minimumReleaseAge: 1440
trustPolicy: "no-downgrade"
trustPolicyIgnoreAfter: 525600
strictDepBuilds: true
blockExoticSubdeps: true
verifyDepsBeforeRun: error
allowBuilds:
  "@biomejs/biome": true
  "@playwright/browser-chromium": true
  "@swc/core": true
  esbuild: true

overrides:
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
  prismjs@<1.30.0: ">=1.30.0"
  serialize-javascript@<7.0.5: ">=7.0.5"
  serialize-javascript@<=7.0.2: ">=7.0.3"

catalog:
  "@emotion/react": "^11.11.4"
  "@emotion/styled": "^11.11.5"
  "@mui/icons-material": "^6.1.1"
  "@mui/lab": "^6.0.0-beta.10"
  "@mui/material": "^6.1.1"
  "@mui/system": "^6.1.1"
  "@types/plotly.js": "^2.12.32"
  "@types/react": "^18.2.55"
  "@types/react-dom": "^18.2.18"
  "plotly.js-dist-min": "^2.33.0"
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "typescript": "^5.7.3"
