[package]
name = "optuna-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
fanova = "0.2.0"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.61"
serde-wasm-bindgen = "0.4"

[lib]
crate-type = ["cdylib"]
