name: e2e-standalone-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/e2e-standalone-tests.yml'
      - 'tslib/**.ts'
      - 'tslib/**.tsx'
      - 'tslib/**/package.json'
      - 'standalone_app/**.ts'
      - 'standalone_app/**.tsx'
      - 'standalone_app/package.json'
      - 'standalone_app/tsconfig.json'
      - 'standalone_app/vite.config.js'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9  # v1
        with:
          targets: wasm32-unknown-unknown

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86  # v6.0.10

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '22'

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          uv sync --group test

      - name: Build rustlib for standalone_app
        working-directory: rustlib
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          cargo install wasm-bindgen-cli --version $WASM_BINDGEN_VERSION
          cargo install wasm-opt
          ./build.sh

      - name: Build tslib
        run: make tslib

      - name: Build standalone_app
        working-directory: standalone_app
        run: pnpm exec vite build --outDir dist

      - name: Install the required browsers
        run: uv run playwright install

      - name: Run e2e tests
        run: uv run pytest e2e_tests/test_standalone
