on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'optuna/optuna-dashboard'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9  # v1
        with:
          targets: wasm32-unknown-unknown
      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86  # v6.0.10
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '22'
      - name: Build rustlib for standalone_app
        working-directory: rustlib
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          cargo install wasm-bindgen-cli --version $WASM_BINDGEN_VERSION
          cargo install wasm-opt
          ./build.sh
      - name: Build tslib
        run: make tslib
      - name: Build standalone_app
        working-directory: standalone_app
        run: |
          pnpm install --frozen-lockfile
          pnpm exec vite build --base=/optuna-dashboard/ --outDir ./gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5.0.0
        with:
          path: './standalone_app/gh-pages'
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'optuna/optuna-dashboard'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128  # v5.0.0
