name: Build Python distributions and create GitHub Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  github-release:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa  # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: '22'

      - name: Install uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff  # v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv venv
          uv pip install wheel twine build

      - run: make python-package
      - run: uv run twine check dist/*

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
          cp ./optuna_dashboard/public/bundle.js ./dist/
          cp ./optuna_dashboard/public/bundle.js.LICENSE.txt ./dist/
          gh release create ${TAGNAME} --draft dist/*
