name: Build Python distributions and create GitHub Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  github-release:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86  # v6.0.10

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '22'

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv venv
          uv pip install wheel twine build

      - run: make python-package
      - run: uv run twine check dist/*

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
          cp ./optuna_dashboard/public/bundle.js ./dist/
          cp ./optuna_dashboard/public/bundle.js.LICENSE.txt ./dist/
          gh release create ${TAGNAME} --draft dist/*
