name: Build Python distributions and publish to PyPI

on:
  release:
    types:
      - published

jobs:
  pypi:
    name: Build and publish Python distributions to PyPI
    if: ${{ startsWith(github.event.release.tag_name, 'v') && !startsWith(github.event.release.tag_name, 'jupyterlab-v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Setup pnpm
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86  # v6.0.10
      with:
        cache: false
    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
      with:
        node-version: '24'
    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      with:
        python-version: '3.13'
        enable-cache: 'false'
        restore-cache: 'false'
        cache-python: 'false'
    - name: Install dependencies
      run: |
        uv venv
        uv pip install wheel twine build

    - run: make python-package

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
      with:
        # See https://github.com/pypa/gh-action-pypi-publish/issues/283
        attestations: false

