name: rust-checks
on:
  pull_request:
    paths:
      - '.github/workflows/rust-tests.yml'
      - 'rustlib/**'

permissions:
  contents: read

jobs:
  test:
    name: Unit tests for rustlib
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Run tests
        working-directory: rustlib
        run: cargo test
