name: typescript-checks
on:
  pull_request:
    paths:
      - '.github/workflows/typescript-tests.yml'
      - '.eslintrc.js'
      - 'biome.json'
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'optuna_dashboard/package.json'
      - 'vscode/package.json'
      - 'standalone_app/package.json'
      - 'tslib/react/package.json'
      - 'tslib/storage/package.json'
      - 'tslib/types/package.json'
      - 'rustlib/Cargo.toml'
      - 'rustlib/Cargo.lock'
      - 'rustlib/**.rs'
      - 'optuna_dashboard/tsconfig.json'
      - 'optuna_dashboard/tsconfig.pkg.json'
      - 'optuna_dashboard/webpack.config.js'
jobs:
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  type-check:
    name: Type checking on optuna-dashboard & standalone_app
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build rustlib
        working-directory: rustlib
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          cargo install wasm-bindgen-cli --version $WASM_BINDGEN_VERSION
          cargo install wasm-opt
          ./build.sh

      - name: Setup tslib
        run: make tslib

      - name: Type Check optuna_dashboard
        run: pnpm --filter @optuna/optuna-dashboard run type-check

      - name: Build rustlib for standalone_app
        working-directory: rustlib
        run: ./build.sh

      - name: Type Check standalone_app
        run: pnpm --filter optuna-dashboard-wasm run type-check

  check-pnpm-lock:
    name: Check pnpm-lock.yaml
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # `pnpm install --frozen-lockfile` exits non-zero when package.json and pnpm-lock.yaml drift
      - run: pnpm install --frozen-lockfile

  build:
    name: JS build check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Build rustlib for standalone_app
        working-directory: rustlib
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          cargo install wasm-bindgen-cli --version $WASM_BINDGEN_VERSION
          cargo install wasm-opt
          ./build.sh

      - name: Setup tslib
        run: make tslib

      - name: Build standalone_app for vscode extension
        run: pnpm --filter optuna-dashboard-wasm run build:vscode

      - name: Build standalone_app for GitHub pages
        working-directory: standalone_app
        run: pnpm exec vite build --out-dir ./gh-pages

      - name: Build bundle.js
        run: |
          pnpm --filter @optuna/optuna-dashboard run build:dev
          pnpm --filter @optuna/optuna-dashboard run build:prd

      - name: Build optuna_dashboard package (for Jupyter Lab extension)
        run: pnpm --filter @optuna/optuna-dashboard run build:pkg

  test-tslib:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: Generate test asset for storage
        working-directory: tslib/storage/test/
        run: |
          python -m pip install --upgrade pip setuptools
          pip install optuna
          python generate_assets.py

      - name: Generate test asset for react
        working-directory: tslib/react/test/
        run: |
          python generate_assets.py

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build test
        run: make tslib

      - name: Run tslib test for storage
        run: pnpm --filter @optuna/storage run test

      - name: Install Playwright Browsers
        working-directory: tslib/react
        run: pnpm exec playwright install --with-deps

      - name: Run tslib test for react
        run: pnpm --filter @optuna/react run test
